#All persistence playbook
  
- import_playbook: ../privilege-escalation/T1015.yaml
  # AVAILABE TAGS:  OSK,SETHC,UTILMAN,MAGNIFY,NARRATOR,DISPLAYSWITCH,ATBROKER
  ignore_errors: yes
- import_playbook: T1031.yaml
  ignore_errors: yes
- import_playbook: T1037.yaml
  ignore_errors: yes
- import_playbook: T1042.yaml
  ignore_errors: yes
- import_playbook: T1050.yaml
  # AVAILABE TAGS:  CMD,PSH
  ignore_errors: yes
- import_playbook: T1053.yaml
  ignore_errors: yes
- import_playbook: T1060.yaml
  # AVAILABLE TAGS: STARTUP, HKLMRUN, HKCURUN
  ignore_errors: yes
- import_playbook: T1084.yaml
  ignore_errors: yes
- import_playbook: T1128.yaml
  ignore_errors: yes
- import_playbook: T1136.yaml
  ignore_errors: yes
- import_playbook: T1158.yaml
  ignore_errors: yes
- import_playbook: T1168.yaml
  ignore_errors: yes
- import_playbook: T1180.yaml
  ignore_errors: yes
- import_playbook: T1183.yaml
  ignore_errors: yes

- name: Generate report
  hosts: windows
  tasks:
    - name: check if windows defender is activated
      tags: always
      win_shell: Get-MpPreference | findstr DisableRealtimeMonitoring
      register: WindowsDefender
    - name: debug msg for windows defender turn on
      tags: always
      debug: msg="Playbook ran#PRIV-ESCALATION-WIN-DEFENDER#"
      when: '"False" in WindowsDefender.stdout'  
    - name: debug msg for defense turn off
      tags: always
      debug: msg="Playbook ran#PRIV-ESCALATION-NO-AV-EDR#"
      when: '"True" in WindowsDefender.stdout'
    - name: Generate report
      tags: always
      command: python3 /opt/ansible/report.py
      delegate_to: localhost
