- name: T1084 - Windows Management Instrumentation Event Subscription - Part 2
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
        - name: Check if startup file exist exist
          tags: always
          win_stat:
            path: C:\temp\{{ victim_file }}
          register: T1084
        
        - name: check if playbook was blocked
          tags: always
          debug: msg="Playbook Completed#T1084#blocked#win#"
          when: T1084.stat.exists == False        
        - name: check if playbook was successfull
          tags: always
          debug: msg="Playbook Completed#T1084#passed#win#"
          when: T1084.stat.exists    
          
        - name: cleanup WMI SUB      
          tags: always
          win_shell: |
            $EventConsumerToCleanup = Get-WmiObject -Namespace root/subscription -Class CommandLineEventConsumer -Filter "Name = 'Backdoor-Consumer'"
            $EventFilterToCleanup = Get-WmiObject -Namespace root/subscription -Class __EventFilter -Filter "Name = 'Backdoor-Logon-Filter'"
            $FilterConsumerBindingToCleanup = Get-WmiObject -Namespace root/subscription -Query "REFERENCES OF {$($EventConsumerToCleanup.__RELPATH)} WHERE ResultClass = __FilterToConsumerBinding"
            $FilterConsumerBindingToCleanup | Remove-WmiObject
            $EventConsumerToCleanup | Remove-WmiObject
            $EventFilterToCleanup | Remove-WmiObject
          when: T1084.stat.exists
          
        - name: cleanup temp fie      
          tags: always
          win_file:
            path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\Notepad.lnk
            state: absent
          when: T1084.stat.exists 
