# attack_technique: T1158
- name: Hidden Files and Directories
  hosts: linux
  tasks:
        - name: Create a hidden file in a hidden directory
          file: path=.{{ victim_folder }}-hidden state=directory
        - name: create hidden file
          shell: |
                echo "this file is hidden" > .{{ victim_folder }}-hidden/.{{ victim_file }}-hidden
        - name: Hidden file mv file to a .file
          shell: |
                cp /etc/shadow .{{ victim_folder }}-hidden/.{{ victim_file }}
        - name: Create visible Directories
          file: path={{ victim_folder }}-visible state=directory
        - name: create visible file
          shell: |
                echo "this file is visible" > {{ victim_folder }}-visible/{{ victim_file }}-visible
