# attack_technique: T1158
- name: Hidden Files and Directories
  hosts: linux
  tasks:
        - name: Create a hidden file in a hidden directory
          file: path=.hidden-directory state=directory
        - name: create hidden file
          shell: |
                echo "this file is hidden" > .hidden-directory/.hidden-file
        - name: Hidden file mv file to a .file
          shell: |
                cp /etc/shadow /tmp/.evil
        - name: Create visible Directories
          file: path=visible-directory state=directory
        - name: create visible file
          shell: |
                echo "this file is visible" > visible-directory/visible-file
