# attack_technique: T1183
- name: T1183 - Image File Execution Options Injection
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
 
  - name: cleanup HKCURUN      
    tags: always
    win_regedit:
        path: HKCU:\SOFTWARE\Classes\CLSID
        state: absent
    when: T1183.exists
         
