#All defensive-evasion playbook

#- import_playbook: T1099.yaml
#  ignore_errors: yes
#- import_playbook: T1117.yaml
#  ignore_errors: yes
#- import_playbook: T1146.yaml
#  ignore_errors: yes
#- import_playbook: T1148.yaml
#  ignore_errors: yes
- import_playbook: T1170.yaml
  ignore_errors: yes

- name: Generate report
  hosts: windows
  tasks:
    - name: check if windows defender is activated
      tags: always
      win_shell: Get-MpPreference | findstr DisableRealtimeMonitoring
      register: WindowsDefender
    - name: debug msg for windows defender turn on
      tags: always
      debug: msg="Playbook ran#DEF-EVASION-WIN-DEFENDER#"
      when: '"False" in WindowsDefender.stdout'  
    - name: debug msg for defense turn off
      tags: always
      debug: msg="Playbook ran#DEF-EVASION-NO-AV-EDR#"
      when: '"True" in WindowsDefender.stdout'
    - name: Generate report
      tags: always
      command: python3 /opt/ansible/report.py
      delegate_to: localhost	
