# attack_technique: T1089
- name: Disabling Security Tools
  hosts: linux
  tasks:
          - name: disable syslog
            tags: SYSLOG
            shell: |
              service rsyslog stop
          - name: disable ufw
            tags: FW
            shell: |
              ufw disable
          - name: check fw status
            tags: FW
            shell: |
              ufw status | grep Status
            register: T1089
          - name: check if playbook was blocked
            tags: FW
            debug: msg="Playbook Completed:T1089:blocked:linux:"
            when:  '"active" in T1089.stdout'       
          - name: check if playbook was successfull
            tags: FW
            debug: msg="Playbook Completed:T1089:passed:linux:"
            when: '"inactive" in T1089.stdout'                  
