# Playbook-T1099
- name :  Timestomp
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
          - name: Set a file's access and modify timestamp
            shell: |
              touch -am -t 197001010000.00 {{victim_folder }}/{{ victim_file }}


