# Playbook-T1099
- name :  Timestomp
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
          - name: Set a file's access and modify timestamp
            tags: option1
            shell: |
              cp /etc/passwd /tmp/passwd
              touch -am -t 197001010000.00 /tmp/passwd
