# Playbook-T1099
- name :  Timestomp - Linux
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
          - name: Set a file's access and modify timestamp
            shell: |
              touch -am -t 197001010000.00 {{victim_folder }}/{{ victim_file }}

- name :  Timestomp - Windows
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
          - name: Touch a file (creates if not present, updates modification time if present)
            win_file:
              path: c:\temp\{{victim_folder }}\{{ victim_file }}
              state: touch
          - name: Set a file's access and modify timestamp
            win_shell: |
              (Get-Item c:\temp\{{victim_folder }}\{{ victim_file }}).LastAccessTime=$(Get-Date "01/01/1970 06:00 am")
              (Get-Item c:\temp\{{victim_folder }}\{{ victim_file }}).LastWriteTime=$(Get-Date "01/01/1970 06:00 am")
