
# Playbook-T1146
- name : Clear Command History
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
          - name: Clear Bash history (rm)
            tags: option1
            shell: rm ~/.bash_history
          - name: Clear Bash history (echo)
            tags: option2
            shell: echo "" > ~/.bash_history
          - name: Clear Bash history (cat)
            tags: option3
            shell: cat /dev/null > ~/.bash_history
          - name: Clear Bash history (ln dev/null)
            tags: option4
            shell: ln -sf /dev/null ~/.bash_history
          - name: Clear Bash history (truncate)
            tags: option5
            shell: truncate -s0 ~/.bash_history
          - name: Clear Bash history (truncate)
            tags: option6
            shell: |
              - unset HISTFILE
              - export HISTFILESIZE=0
              - history -c
          - name: check files there
            tags: always
            stat:
              path: ~/.bash_history
            register: T1146
          - name: check if playbook was blocked
            tags: always
            debug: msg="Playbook Completed:T1146:blocked:linux:"
            when: (T1146.stat.exists == False or T1146.stat.size > 2)
          - name: check if playbook was successfull
            tags: always
            debug: msg="Playbook Completed:T1146:passed:linux:"
            when: (T1146.stat.exists and T1146.stat.size < 2)
           
