# Playbook-T11148
# check if command don't show in ~/.bash_history
- name : HISTCONTROL
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
          - name: disable history
            shell: |
              export HISTCONTROL=ignoreboth
              echo export "HISTCONTROL=ignoreboth" >> ~/.bash_profile
          - name: execute hidden commands
            shell: |
              {{ nohistory_command }}
              export HISTCONTROL=
              
