
# Playbook-T1146
- name : Clear Command History
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
          - name: Clear Bash history (rm)
            tags: option1
            shell: rm ~/.bash_history
          - name: Clear Bash history (rm)
            tags: option2
            shell: echo "" > ~/.bash_history
          - name: Clear Bash history (rm)
            tags: option3
            shell: cat /dev/null > ~/.bash_history
          - name: Clear Bash history (ln dev/null)
            tags: option4
            shell: ln -sf /dev/null ~/.bash_history
          - name: Clear Bash history (truncate)
            tags: option5
            shell: truncate -s0 ~/.bash_history
          - name: Clear Bash history (truncate)
            tags: option6
            shell: |
              - unset HISTFILE
              - export HISTFILESIZE=0
              - history -c
            
           
