#All privilege-escalation playbook
- name: output msg based on tag
  hosts: windows
  tasks:
    - name: debug msg for defensive turn on
      tags: WDEFENDER
      debug: msg="Playbook ran with#PRIV-ESCALATION-WIN-DEFENDER#"
      
    - name: Run handlers only
      tags: NOTHING
      debug: msg="Playbook ran without#PRIV-ESCALATION-NO-AV-EDR#"
  
- import_playbook: T1015.yaml
  # AVAILABE TAGS:  OSK,SETHC,UTILMAN,MAGNIFY,NARRATOR,DISPLAYSWITCH,ATBROKER
  ignore_errors: yes
- import_playbook: T1088.yaml
  ignore_errors: yes

- name: Generate report
  hosts: windows
  tasks:
    - name: Generate report
      tags: always
      command: /opt/ansible/python3 report.py
      delegate_to: localhost	
