# attack_technique: T1138
- name: T1138 - Application Shimming
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
    - name: copy putty32 bit version
      tags: always
      win_copy:
        src: /opt/ansible/putty32.exe
        dest: c:\temp\
    - name: copy dll
      tags: always
      win_copy:
        src: /opt/ansible/putty32.exe
        dest: c:\temp\  
    - name: install shim
      win_command: |
        sdbinst puttyfix32.sdb    
      register: shim
    - name: Execute putty32
      tags: always
      win_command: |
        cd c:\temp
        cmd.exe /k putty32.exe
        
    - name: sleep for 10 seconds and continue with play to check if AV removed or Not
      tags: always
      wait_for: timeout=10
      delegate_to: localhost

    - name: check file exist
      tags: always
      win_stat:
        path: c:\temp\evil.txt
      register: T1138
    - name: check if playbook was blocked
      tags: always
      debug: msg="Playbook Completed#T1138#blocked#win#"
      when: T1138.stat.exists == False        
    - name: check if playbook was successfull
      tags: always
      debug: msg="Playbook Completed#T1138#passed#win#"
      when: T1138.stat.exists 
      
    - name: cleanup      
      tags: alawys
      win_file:
        path: c:\temp\evil.txt
        state: absent
      when: T1138.stat.exists 
