#All discovery playbook

- import_playbook: T1018.yaml
  ignore_errors: yes

- import_playbook: T1046.yaml
  # AVAILABE TAGS:  SSH,SMB
  ignore_errors: yes

- name: Generate report
  hosts: windows
  tasks:
    - name: check if windows defender is activated
      tags: always
      win_shell: Get-MpPreference | findstr DisableRealtimeMonitoring
      register: WindowsDefender
    - name: debug msg for windows defender turn on
      tags: always
      debug: msg="Playbook ran#PRIV-ESCALATION-WIN-DEFENDER#"
      when: '"False" in WindowsDefender.stdout'  
    - name: debug msg for defense turn off
      tags: always
      debug: msg="Playbook ran#PRIV-ESCALATION-NO-AV-EDR#"
      when: '"True" in WindowsDefender.stdout'
    - name: Generate report
      tags: always
      command: python3 /opt/ansible/report.py
      delegate_to: localhost
