# attack_technique: T1046
- name: Network Service Scanning
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
         - name: Network Service Scanning - SSH
           tags: SSH
           shell: >
              subnet=\`ifconfig | grep \'inet \' | awk \'{print $2}\' | sed -e \'/^127.0.0.1/d\' | cut -d \".\" -f1-3\`
 
