# Playbook-T1002
- name : attacktechniqueT1002
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
          - name: compress-files
            file: 
              path={{ item }}  state=directory
              state=directory
            with_items:
              - "{{ victim_folder }}"
              - "{{ exfiltration_folder }}"
          - name: createfiles
            shell: |
                cd {{ victim_folder }}
                touch a b c d e f g h
                echo "This file will be gzipped" > /tmp/{{ victim_file }}-gzip.txt
                echo "This file will be tarred" > /tmp/{{ victim_file }}-tar.txt
                zip {{ exfiltration_folder }}/{{ exfiltration_file }}.zip {{ victim_folder }}/*
                gzip -f /tmp/{{ victim_file }}-gzip.txt >> {{ exfiltration_folder }}/{{ exfiltration_file }}.gzip
                tar -cvzf {{ exfiltration_folder }}/{{ exfiltration_file }}-gzip.tar.gz {{ victim_folder }}
          - name: delete temp files
            shell: |
                rm -r {{ victim_folder }}
                rm /tmp/{{ victim_file }}-gzip.txt
                rm /tmp/{{ victim_file }}-tar.txt
                rm /tmp/{{ victim_file }}-gzip.txt.gz
          - name: check files there
            tags: always
            stat:
              path: "{{ exfiltration_folder }}/{{ exfiltration_file }}.gzip"
            register: T1002
          - name: check if playbook was blocked
            tags: always
            debug: msg="Playbook Completed:T1002:blocked:linux:"
            when: T1002.exists == False        
          - name: check if playbook was successfull
            tags: always
            debug: msg="Playbook Completed:T1002:passed:linux:"
            when: T1002.exists      
